name: Pylint

on:
  push:
    branches:
      - changes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 bandit mypy pip-audit
    - name: Analysing the code with pylint
      if: always()
      run: |
        pylint $(git ls-files '*.py')
    - name: using flake8
      if: always()
      run: |
        flake8 $(git ls-files '*.py')
    - name: using bandit
      if: always()
      run: |
        bandit -r Project1
    - name: using mypy
      if: always()
      run: |
        mypy $(git ls-files '*.py')
    - name: using pip-audit
      if: always()
      run: |
        pip-audit
